spring.application.name=api

jwt.secret=change_this_jwt_secret_please_replace_with_a_long_random_value_please_replace_with_a_random_very_long_string_1234567890
jwt.expiration-ms=86400000

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:cemsdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
